services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Password123!}
      POSTGRES_DB: ${POSTGRES_DB:-test}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
        ]
      interval: 1s
      timeout: 5s
      retries: 10
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
  cache:
    image: redis
    restart: always
    # image: docker.dragonflydb.io/dragonflydb/dragonfly
    # image: eqalpha/keydb
    ports:
      - "${REDIS_PORT:-6379}:6379"