root = "."
tmp_dir = "tmp_air"

[build]
  bin = "./tmp_air/main.exe"
  cmd = "just.exe build-air"
  delay = 1000
  exclude_dir = ["public", "schema", "tmp_air", "vendor", "node_modules"]
  exclude_file = []
  exclude_regex = [".*_templ\\.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "ts"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[proxy]
  # Enable live-reloading on the browser "localhost:$proxy_port"
  enabled = true
  proxy_port = 8081
  app_port = 8080